# Generated by Django 5.0.6 on 2024-06-23 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('medicine', models.JSONField(blank=True, default=list, null=True)),
                ('gid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('conditions', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
