# Generated by Django 5.0.6 on 2024-06-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_contact_mails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='medicine',
            new_name='medicine_0',
        ),
        migrations.AddField(
            model_name='user',
            name='medicine_1',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='medicine_2',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
